---
title: Título principal
subtitle: Subtítulo
author: Nombre del autor
email: email del autor
institute: Universidad Técnica Federico Santa María
professor: Profesor
course: Asignatura
other_langs: en
bibliography: bibliography.bib
biblio-style: "apalike"
biblio-title: Referencias
date: \today
theme: guadec
classoption: aspectratio=169
header-includes:
    - \widowpenalties 1 150
    - \usepackage[spanish, es-tabla]{babel}
output:
  beamer_presentation:
      citation_package: natbib
---
